# Generated by Django 4.2 on 2024-06-01 12:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'گالری', 'verbose_name_plural': 'گالری'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
