# Generated by Django 4.2 on 2024-05-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hit',
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
