# Generated by Django 4.2 on 2024-06-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_hit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'وبلاگ', 'verbose_name_plural': 'بلاگ ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی وبلاگ', 'verbose_name_plural': 'دسته بندی بلاگ'},
        ),
    ]
