# Generated by Django 4.2 on 2024-04-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/service/category/%m/%d'),
        ),
    ]
