# Generated by Django 4.2 on 2024-04-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_category_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='icon_b',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image2',
            new_name='icon_w',
        ),
    ]
