# Generated by Django 4.2 on 2024-04-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_category_description'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('lid', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('film', models.FileField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('text1', models.CharField(max_length=120)),
                ('text2', models.CharField(max_length=120)),
                ('text3', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'section1',
                'verbose_name_plural': 'sections1',
            },
        ),
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('lid', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('text', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'section2',
                'verbose_name_plural': 'sections2',
            },
        ),
        migrations.CreateModel(
            name='Section3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('lid', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'section3',
                'verbose_name_plural': 'sections3',
            },
        ),
        migrations.CreateModel(
            name='Section5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('lid', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'section5',
                'verbose_name_plural': 'sections5',
            },
        ),
        migrations.CreateModel(
            name='Section6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('lid', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'section6',
                'verbose_name_plural': 'sections6',
            },
        ),
        migrations.CreateModel(
            name='Section4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('lid', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('film', models.FileField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('text_ok', models.CharField(max_length=120)),
                ('icon_ok', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('num_ok', models.PositiveBigIntegerField()),
                ('text_project', models.CharField(max_length=120)),
                ('icon_project', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('num_project', models.PositiveBigIntegerField()),
                ('text_tajrobe', models.CharField(max_length=120)),
                ('icon_tajrobe', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('num_tajrobe', models.PositiveBigIntegerField()),
                ('text_person', models.CharField(max_length=120)),
                ('icon_person', models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/')),
                ('num_person', models.PositiveBigIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_section', to='service.category')),
            ],
            options={
                'verbose_name': 'section4',
                'verbose_name_plural': 'sections4',
            },
        ),
    ]
