# Generated by Django 4.2 on 2024-04-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_section1_section2_section3_section5_section6_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section2',
            old_name='icon',
            new_name='icon1',
        ),
        migrations.RenameField(
            model_name='section2',
            old_name='text',
            new_name='text1',
        ),
        migrations.AddField(
            model_name='section2',
            name='icon2',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/'),
        ),
        migrations.AddField(
            model_name='section2',
            name='text2',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
