# Generated by Django 4.2 on 2024-04-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_icon_section2_icon1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section2',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/'),
        ),
        migrations.AddField(
            model_name='section2',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/index/%m/%d/'),
        ),
    ]
