# Generated by Django 4.2 on 2024-04-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_section2_image3_section2_image4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section4',
            name='category',
        ),
    ]
